[package]
name = "pebble-engine"
version = "3.1.2"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A modular, ECS-style graphics/app framework for Rust."
repository = "https://github.com/Akihiro120/pebble"
readme = "Readme.md"
keywords = ["graphics", "ecs", "gamedev"]
categories = ["graphics", "game-engines"]

[lib]
name = "pebble"

[dependencies]
hecs = "0.11.0"
slotmap = "1.1.1"
tracing = "0.1"
wgpu = { version = "30.0.0", features = ["spirv", "fragile-send-sync-non-atomic-wasm"] }
winit = "0.30"
winit_input_helper = "0.17"
image = "0.25.10"
half = "2.4"
bytemuck = { version = "1.25.2", features = ["derive"] }
glam = { version = "0.32", features = ["bytemuck", "encase"] }
tracing-subscriber = "0.3.23"
futures = "0.3"
oneshot = "0.2.1"
web-time = "1.1"
encase = "0.12"
pebble-derive = { path = "pebble-derive", version = "2.7.3" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "1.0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Element", "HtmlCanvasElement", "DomRect"] }
wasm-bindgen-futures = "0.4"
